FROM golang:1.26.1-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o mqtt-driver ./cmd/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/mqtt-driver .

EXPOSE 8000

ENTRYPOINT ["./mqtt-driver"]