name: Teste de Deploy com Coolify

on: 
  push: 
    branches: ["prod"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:  
      - name: Send to Coolify
        run: curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}'
