name: Teste de Deploy com Coolify

on: 
  push: 
    branches: ["prod"]

jobs:
  deploy:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:  
      - name: Send to Coolify
        run: |
          curl -f -s -S --request GET '${{ secrets.COOLIFY_WEBHOOK }}'
          --header 'Authorization: Bearer ${{secrets.COOLIFY_TOKEN}}'
